package github.ankushsachdeva.emojicon.emoji_default;

public class Nature {
    public static final String[] DATA = new String[]{
            EmojiDefault.getEmojiByUnicode(0x1f436),
            EmojiDefault.getEmojiByUnicode(0x1f43a),
            EmojiDefault.getEmojiByUnicode(0x1f431),
            EmojiDefault.getEmojiByUnicode(0x1f42d),
            EmojiDefault.getEmojiByUnicode(0x1f439),
            EmojiDefault.getEmojiByUnicode(0x1f430),
            EmojiDefault.getEmojiByUnicode(0x1f438),
            EmojiDefault.getEmojiByUnicode(0x1f42f),
            EmojiDefault.getEmojiByUnicode(0x1f428),
            EmojiDefault.getEmojiByUnicode(0x1f43b),
            EmojiDefault.getEmojiByUnicode(0x1f437),
            EmojiDefault.getEmojiByUnicode(0x1f43d),
            EmojiDefault.getEmojiByUnicode(0x1f42e),
            EmojiDefault.getEmojiByUnicode(0x1f417),
            EmojiDefault.getEmojiByUnicode(0x1f435),
            EmojiDefault.getEmojiByUnicode(0x1f412),
            EmojiDefault.getEmojiByUnicode(0x1f434),
            EmojiDefault.getEmojiByUnicode(0x1f411),
            EmojiDefault.getEmojiByUnicode(0x1f418),
            EmojiDefault.getEmojiByUnicode(0x1f43c),
            EmojiDefault.getEmojiByUnicode(0x1f427),
            EmojiDefault.getEmojiByUnicode(0x1f426),
            EmojiDefault.getEmojiByUnicode(0x1f424),
            EmojiDefault.getEmojiByUnicode(0x1f425),
            EmojiDefault.getEmojiByUnicode(0x1f423),
            EmojiDefault.getEmojiByUnicode(0x1f414),
            EmojiDefault.getEmojiByUnicode(0x1f40d),
            EmojiDefault.getEmojiByUnicode(0x1f422),
            EmojiDefault.getEmojiByUnicode(0x1f41b),
            EmojiDefault.getEmojiByUnicode(0x1f41d),
            EmojiDefault.getEmojiByUnicode(0x1f41c),
            EmojiDefault.getEmojiByUnicode(0x1f41e),
            EmojiDefault.getEmojiByUnicode(0x1f40c),
            EmojiDefault.getEmojiByUnicode(0x1f419),
            EmojiDefault.getEmojiByUnicode(0x1f41a),
            EmojiDefault.getEmojiByUnicode(0x1f420),
            EmojiDefault.getEmojiByUnicode(0x1f41f),
            EmojiDefault.getEmojiByUnicode(0x1f42c),
            EmojiDefault.getEmojiByUnicode(0x1f433),
            EmojiDefault.getEmojiByUnicode(0x1f40b),
            EmojiDefault.getEmojiByUnicode(0x1f404),
            EmojiDefault.getEmojiByUnicode(0x1f40f),
            EmojiDefault.getEmojiByUnicode(0x1f400),
            EmojiDefault.getEmojiByUnicode(0x1f403),
            EmojiDefault.getEmojiByUnicode(0x1f405),
            EmojiDefault.getEmojiByUnicode(0x1f407),
            EmojiDefault.getEmojiByUnicode(0x1f409),
            EmojiDefault.getEmojiByUnicode(0x1f40e),
            EmojiDefault.getEmojiByUnicode(0x1f410),
            EmojiDefault.getEmojiByUnicode(0x1f413),
            EmojiDefault.getEmojiByUnicode(0x1f415),
            EmojiDefault.getEmojiByUnicode(0x1f416),
            EmojiDefault.getEmojiByUnicode(0x1f401),
            EmojiDefault.getEmojiByUnicode(0x1f402),
            EmojiDefault.getEmojiByUnicode(0x1f432),
            EmojiDefault.getEmojiByUnicode(0x1f421),
            EmojiDefault.getEmojiByUnicode(0x1f40a),
            EmojiDefault.getEmojiByUnicode(0x1f42b),
            EmojiDefault.getEmojiByUnicode(0x1f42a),
            EmojiDefault.getEmojiByUnicode(0x1f406),
            EmojiDefault.getEmojiByUnicode(0x1f408),
            EmojiDefault.getEmojiByUnicode(0x1f429),
            EmojiDefault.getEmojiByUnicode(0x1f43e),
            EmojiDefault.getEmojiByUnicode(0x1f490),
            EmojiDefault.getEmojiByUnicode(0x1f338),
            EmojiDefault.getEmojiByUnicode(0x1f337),
            EmojiDefault.getEmojiByUnicode(0x1f340),
            EmojiDefault.getEmojiByUnicode(0x1f339),
            EmojiDefault.getEmojiByUnicode(0x1f33b),
            EmojiDefault.getEmojiByUnicode(0x1f33a),
            EmojiDefault.getEmojiByUnicode(0x1f341),
            EmojiDefault.getEmojiByUnicode(0x1f343),
            EmojiDefault.getEmojiByUnicode(0x1f342),
            EmojiDefault.getEmojiByUnicode(0x1f33f),
            EmojiDefault.getEmojiByUnicode(0x1f33e),
            EmojiDefault.getEmojiByUnicode(0x1f344),
            EmojiDefault.getEmojiByUnicode(0x1f335),
            EmojiDefault.getEmojiByUnicode(0x1f334),
            EmojiDefault.getEmojiByUnicode(0x1f332),
            EmojiDefault.getEmojiByUnicode(0x1f333),
            EmojiDefault.getEmojiByUnicode(0x1f330),
            EmojiDefault.getEmojiByUnicode(0x1f331),
            EmojiDefault.getEmojiByUnicode(0x1f33c),
            EmojiDefault.getEmojiByUnicode(0x1f310),
            EmojiDefault.getEmojiByUnicode(0x1f31e),
            EmojiDefault.getEmojiByUnicode(0x1f31d),
            EmojiDefault.getEmojiByUnicode(0x1f31a),
            EmojiDefault.getEmojiByUnicode(0x1f311),
            EmojiDefault.getEmojiByUnicode(0x1f312),
            EmojiDefault.getEmojiByUnicode(0x1f313),
            EmojiDefault.getEmojiByUnicode(0x1f314),
            EmojiDefault.getEmojiByUnicode(0x1f315),
            EmojiDefault.getEmojiByUnicode(0x1f316),
            EmojiDefault.getEmojiByUnicode(0x1f317),
            EmojiDefault.getEmojiByUnicode(0x1f318),
            EmojiDefault.getEmojiByUnicode(0x1f31c),
            EmojiDefault.getEmojiByUnicode(0x1f31b),
            EmojiDefault.getEmojiByUnicode(0x1f319),
            EmojiDefault.getEmojiByUnicode(0x1f30d),
            EmojiDefault.getEmojiByUnicode(0x1f30e),
            EmojiDefault.getEmojiByUnicode(0x1f30f),
            EmojiDefault.getEmojiByUnicode(0x1f30b),
            EmojiDefault.getEmojiByUnicode(0x1f30c),
            EmojiDefault.getEmojiByUnicode(0x1f320),
            String.valueOf((char) 0x2b50),
            String.valueOf((char) 0x2600),
            String.valueOf((char) 0x26c5),
            String.valueOf((char) 0x2601),
            String.valueOf((char) 0x26a1),
            String.valueOf((char) 0x2614),
            String.valueOf((char) 0x2744),
            String.valueOf((char) 0x26c4),
            EmojiDefault.getEmojiByUnicode(0x1f300),
            EmojiDefault.getEmojiByUnicode(0x1f301),
            EmojiDefault.getEmojiByUnicode(0x1f308),
            EmojiDefault.getEmojiByUnicode(0x1f30a),
    };
}
