package github.ankushsachdeva.emojicon.emoji_default;

import github.ankushsachdeva.emojicon.emoji.Emojicon;

public class Places {
    public static final String[] DATA = new String[]{
            EmojiDefault.getEmojiByUnicode(0x1f3e0),
            EmojiDefault.getEmojiByUnicode(0x1f3e1),
            EmojiDefault.getEmojiByUnicode(0x1f3eb),
            EmojiDefault.getEmojiByUnicode(0x1f3e2),
            EmojiDefault.getEmojiByUnicode(0x1f3e3),
            EmojiDefault.getEmojiByUnicode(0x1f3e5),
            EmojiDefault.getEmojiByUnicode(0x1f3e6),
            EmojiDefault.getEmojiByUnicode(0x1f3ea),
            EmojiDefault.getEmojiByUnicode(0x1f3e9),
            EmojiDefault.getEmojiByUnicode(0x1f3e8),
            EmojiDefault.getEmojiByUnicode(0x1f492),
            String.valueOf((char) 0x26ea),
            EmojiDefault.getEmojiByUnicode(0x1f3ec),
            EmojiDefault.getEmojiByUnicode(0x1f3e4),
            EmojiDefault.getEmojiByUnicode(0x1f307),
            EmojiDefault.getEmojiByUnicode(0x1f306),
            EmojiDefault.getEmojiByUnicode(0x1f3ef),
            EmojiDefault.getEmojiByUnicode(0x1f3f0),
            String.valueOf((char) 0x26fa),
            EmojiDefault.getEmojiByUnicode(0x1f3ed),
            EmojiDefault.getEmojiByUnicode(0x1f5fc),
            EmojiDefault.getEmojiByUnicode(0x1f5fe),
            EmojiDefault.getEmojiByUnicode(0x1f5fb),
            EmojiDefault.getEmojiByUnicode(0x1f304),
            EmojiDefault.getEmojiByUnicode(0x1f305),
            EmojiDefault.getEmojiByUnicode(0x1f303),
            EmojiDefault.getEmojiByUnicode(0x1f5fd),
            EmojiDefault.getEmojiByUnicode(0x1f309),
            EmojiDefault.getEmojiByUnicode(0x1f3a0),
            EmojiDefault.getEmojiByUnicode(0x1f3a1),
            String.valueOf((char) 0x26f2),
            EmojiDefault.getEmojiByUnicode(0x1f3a2),
            EmojiDefault.getEmojiByUnicode(0x1f6a2),
            String.valueOf((char) 0x26f5),
            EmojiDefault.getEmojiByUnicode(0x1f6a4),
            EmojiDefault.getEmojiByUnicode(0x1f6a3),
            String.valueOf((char) 0x2693),
            EmojiDefault.getEmojiByUnicode(0x1f680),
            String.valueOf((char) 0x2708),
            EmojiDefault.getEmojiByUnicode(0x1f4ba),
            EmojiDefault.getEmojiByUnicode(0x1f681),
            EmojiDefault.getEmojiByUnicode(0x1f682),
            EmojiDefault.getEmojiByUnicode(0x1f68a),
            EmojiDefault.getEmojiByUnicode(0x1f689),
            EmojiDefault.getEmojiByUnicode(0x1f69e),
            EmojiDefault.getEmojiByUnicode(0x1f686),
            EmojiDefault.getEmojiByUnicode(0x1f684),
            EmojiDefault.getEmojiByUnicode(0x1f685),
            EmojiDefault.getEmojiByUnicode(0x1f688),
            EmojiDefault.getEmojiByUnicode(0x1f687),
            EmojiDefault.getEmojiByUnicode(0x1f69d),
            EmojiDefault.getEmojiByUnicode(0x1f68b),
            EmojiDefault.getEmojiByUnicode(0x1f683),
            EmojiDefault.getEmojiByUnicode(0x1f68e),
            EmojiDefault.getEmojiByUnicode(0x1f68c),
            EmojiDefault.getEmojiByUnicode(0x1f68d),
            EmojiDefault.getEmojiByUnicode(0x1f699),
            EmojiDefault.getEmojiByUnicode(0x1f698),
            EmojiDefault.getEmojiByUnicode(0x1f697),
            EmojiDefault.getEmojiByUnicode(0x1f695),
            EmojiDefault.getEmojiByUnicode(0x1f696),
            EmojiDefault.getEmojiByUnicode(0x1f69b),
            EmojiDefault.getEmojiByUnicode(0x1f69a),
            EmojiDefault.getEmojiByUnicode(0x1f6a8),
            EmojiDefault.getEmojiByUnicode(0x1f693),
            EmojiDefault.getEmojiByUnicode(0x1f694),
            EmojiDefault.getEmojiByUnicode(0x1f692),
            EmojiDefault.getEmojiByUnicode(0x1f691),
            EmojiDefault.getEmojiByUnicode(0x1f690),
            EmojiDefault.getEmojiByUnicode(0x1f6b2),
            EmojiDefault.getEmojiByUnicode(0x1f6a1),
            EmojiDefault.getEmojiByUnicode(0x1f69f),
            EmojiDefault.getEmojiByUnicode(0x1f6a0),
            EmojiDefault.getEmojiByUnicode(0x1f69c),
            EmojiDefault.getEmojiByUnicode(0x1f488),
            EmojiDefault.getEmojiByUnicode(0x1f68f),
            EmojiDefault.getEmojiByUnicode(0x1f3ab),
            EmojiDefault.getEmojiByUnicode(0x1f6a6),
            EmojiDefault.getEmojiByUnicode(0x1f6a5),
            String.valueOf((char) 0x26a0),
            EmojiDefault.getEmojiByUnicode(0x1f6a7),
            EmojiDefault.getEmojiByUnicode(0x1f530),
            String.valueOf((char) 0x26fd),
            EmojiDefault.getEmojiByUnicode(0x1f3ee),
            EmojiDefault.getEmojiByUnicode(0x1f3b0),
            String.valueOf((char) 0x2668),
            EmojiDefault.getEmojiByUnicode(0x1f5ff),
            EmojiDefault.getEmojiByUnicode(0x1f3aa),
            EmojiDefault.getEmojiByUnicode(0x1f3ad),
            EmojiDefault.getEmojiByUnicode(0x1f4cd),
            EmojiDefault.getEmojiByUnicode(0x1f6a9),
            String.valueOf("\ud83c\uddef\ud83c\uddf5"),
            String.valueOf("\ud83c\uddf0\ud83c\uddf7"),
            String.valueOf("\ud83c\udde9\ud83c\uddea"),
            String.valueOf("\ud83c\udde8\ud83c\uddf3"),
            String.valueOf("\ud83c\uddfa\ud83c\uddf8"),
            String.valueOf("\ud83c\uddeb\ud83c\uddf7"),
            String.valueOf("\ud83c\uddea\ud83c\uddf8"),
            String.valueOf("\ud83c\uddee\ud83c\uddf9"),
            String.valueOf("\ud83c\uddf7\ud83c\uddfa"),
            String.valueOf("\ud83c\uddec\ud83c\udde7"),
    };
}
