package github.ankushsachdeva.emojicon.emoji_default;

import github.ankushsachdeva.emojicon.emoji.Emojicon;

public class Symbols {
    public static final String[] DATA = new String[]{
            String.valueOf("\u0031\u20e3"),
            String.valueOf("\u0032\u20e3"),
            String.valueOf("\u0033\u20e3"),
            String.valueOf("\u0034\u20e3"),
            String.valueOf("\u0035\u20e3"),
            String.valueOf("\u0036\u20e3"),
            String.valueOf("\u0037\u20e3"),
            String.valueOf("\u0038\u20e3"),
            String.valueOf("\u0039\u20e3"),
            String.valueOf("\u0030\u20e3"),
            EmojiDefault.getEmojiByUnicode(0x1f51f),
            EmojiDefault.getEmojiByUnicode(0x1f522),
            String.valueOf("\u0023\u20e3"),
            EmojiDefault.getEmojiByUnicode(0x1f523),
            String.valueOf((char) 0x2b06),
            String.valueOf((char) 0x2b07),
            String.valueOf((char) 0x2b05),
            String.valueOf((char) 0x27a1),
            EmojiDefault.getEmojiByUnicode(0x1f520),
            EmojiDefault.getEmojiByUnicode(0x1f521),
            EmojiDefault.getEmojiByUnicode(0x1f524),
            String.valueOf((char) 0x2197),
            String.valueOf((char) 0x2196),
            String.valueOf((char) 0x2198),
            String.valueOf((char) 0x2199),
            String.valueOf((char) 0x2194),
            String.valueOf((char) 0x2195),
            EmojiDefault.getEmojiByUnicode(0x1f504),
            String.valueOf((char) 0x25c0),
            String.valueOf((char) 0x25b6),
            EmojiDefault.getEmojiByUnicode(0x1f53c),
            EmojiDefault.getEmojiByUnicode(0x1f53d),
            String.valueOf((char) 0x21a9),
            String.valueOf((char) 0x21aa),
            String.valueOf((char) 0x2139),
            String.valueOf((char) 0x23ea),
            String.valueOf((char) 0x23e9),
            String.valueOf((char) 0x23eb),
            String.valueOf((char) 0x23ec),
            String.valueOf((char) 0x2935),
            String.valueOf((char) 0x2934),
            EmojiDefault.getEmojiByUnicode(0x1f197),
            EmojiDefault.getEmojiByUnicode(0x1f500),
            EmojiDefault.getEmojiByUnicode(0x1f501),
            EmojiDefault.getEmojiByUnicode(0x1f502),
            EmojiDefault.getEmojiByUnicode(0x1f195),
            EmojiDefault.getEmojiByUnicode(0x1f199),
            EmojiDefault.getEmojiByUnicode(0x1f192),
            EmojiDefault.getEmojiByUnicode(0x1f193),
            EmojiDefault.getEmojiByUnicode(0x1f196),
            EmojiDefault.getEmojiByUnicode(0x1f4f6),
            EmojiDefault.getEmojiByUnicode(0x1f3a6),
            EmojiDefault.getEmojiByUnicode(0x1f201),
            EmojiDefault.getEmojiByUnicode(0x1f22f),
            EmojiDefault.getEmojiByUnicode(0x1f233),
            EmojiDefault.getEmojiByUnicode(0x1f235),
            EmojiDefault.getEmojiByUnicode(0x1f234),
            EmojiDefault.getEmojiByUnicode(0x1f232),
            EmojiDefault.getEmojiByUnicode(0x1f250),
            EmojiDefault.getEmojiByUnicode(0x1f239),
            EmojiDefault.getEmojiByUnicode(0x1f23a),
            EmojiDefault.getEmojiByUnicode(0x1f236),
            EmojiDefault.getEmojiByUnicode(0x1f21a),
            EmojiDefault.getEmojiByUnicode(0x1f6bb),
            EmojiDefault.getEmojiByUnicode(0x1f6b9),
            EmojiDefault.getEmojiByUnicode(0x1f6ba),
            EmojiDefault.getEmojiByUnicode(0x1f6bc),
            EmojiDefault.getEmojiByUnicode(0x1f6be),
            EmojiDefault.getEmojiByUnicode(0x1f6b0),
            EmojiDefault.getEmojiByUnicode(0x1f6ae),
            EmojiDefault.getEmojiByUnicode(0x1f17f),
            String.valueOf((char) 0x267f),
            EmojiDefault.getEmojiByUnicode(0x1f6ad),
            EmojiDefault.getEmojiByUnicode(0x1f237),
            EmojiDefault.getEmojiByUnicode(0x1f238),
            EmojiDefault.getEmojiByUnicode(0x1f202),
            String.valueOf((char) 0x24c2),
            EmojiDefault.getEmojiByUnicode(0x1f6c2),
            EmojiDefault.getEmojiByUnicode(0x1f6c4),
            EmojiDefault.getEmojiByUnicode(0x1f6c5),
            EmojiDefault.getEmojiByUnicode(0x1f6c3),
            EmojiDefault.getEmojiByUnicode(0x1f251),
            String.valueOf((char) 0x3299),
            String.valueOf((char) 0x3297),
            EmojiDefault.getEmojiByUnicode(0x1f191),
            EmojiDefault.getEmojiByUnicode(0x1f198),
            EmojiDefault.getEmojiByUnicode(0x1f194),
            EmojiDefault.getEmojiByUnicode(0x1f6ab),
            EmojiDefault.getEmojiByUnicode(0x1f51e),
            EmojiDefault.getEmojiByUnicode(0x1f4f5),
            EmojiDefault.getEmojiByUnicode(0x1f6af),
            EmojiDefault.getEmojiByUnicode(0x1f6b1),
            EmojiDefault.getEmojiByUnicode(0x1f6b3),
            EmojiDefault.getEmojiByUnicode(0x1f6b7),
            EmojiDefault.getEmojiByUnicode(0x1f6b8),
            String.valueOf((char) 0x26d4),
            String.valueOf((char) 0x2733),
            String.valueOf((char) 0x2747),
            String.valueOf((char) 0x274e),
            String.valueOf((char) 0x2705),
            String.valueOf((char) 0x2734),
            EmojiDefault.getEmojiByUnicode(0x1f49f),
            EmojiDefault.getEmojiByUnicode(0x1f19a),
            EmojiDefault.getEmojiByUnicode(0x1f4f3),
            EmojiDefault.getEmojiByUnicode(0x1f4f4),
            EmojiDefault.getEmojiByUnicode(0x1f170),
            EmojiDefault.getEmojiByUnicode(0x1f171),
            EmojiDefault.getEmojiByUnicode(0x1f18e),
            EmojiDefault.getEmojiByUnicode(0x1f17e),
            EmojiDefault.getEmojiByUnicode(0x1f4a0),
            String.valueOf((char) 0x27bf),
            String.valueOf((char) 0x267b),
            String.valueOf((char) 0x2648),
            String.valueOf((char) 0x2649),
            String.valueOf((char) 0x264a),
            String.valueOf((char) 0x264b),
            String.valueOf((char) 0x264c),
            String.valueOf((char) 0x264d),
            String.valueOf((char) 0x264e),
            String.valueOf((char) 0x264f),
            String.valueOf((char) 0x2650),
            String.valueOf((char) 0x2651),
            String.valueOf((char) 0x2652),
            String.valueOf((char) 0x2653),
            String.valueOf((char) 0x26ce),
            EmojiDefault.getEmojiByUnicode(0x1f52f),
            EmojiDefault.getEmojiByUnicode(0x1f3e7),
            EmojiDefault.getEmojiByUnicode(0x1f4b9),
            EmojiDefault.getEmojiByUnicode(0x1f4b2),
            EmojiDefault.getEmojiByUnicode(0x1f4b1),
//            Emoji.fromChar((char)0x00a9),
//            Emoji.fromChar((char)0x00ae),
            String.valueOf((char) 0xe24e),
            String.valueOf((char) 0xe24f),

            String.valueOf((char) 0x2122),
            String.valueOf((char) 0x274c),
            String.valueOf((char) 0x203c),
            String.valueOf((char) 0x2049),
            String.valueOf((char) 0x2757),
            String.valueOf((char) 0x2753),
            String.valueOf((char) 0x2755),
            String.valueOf((char) 0x2754),
            String.valueOf((char) 0x2b55),
            EmojiDefault.getEmojiByUnicode(0x1f51d),
            EmojiDefault.getEmojiByUnicode(0x1f51a),
            EmojiDefault.getEmojiByUnicode(0x1f519),
            EmojiDefault.getEmojiByUnicode(0x1f51b),
            EmojiDefault.getEmojiByUnicode(0x1f51c),
            EmojiDefault.getEmojiByUnicode(0x1f503),
            EmojiDefault.getEmojiByUnicode(0x1f55b),
            EmojiDefault.getEmojiByUnicode(0x1f567),
            EmojiDefault.getEmojiByUnicode(0x1f550),
            EmojiDefault.getEmojiByUnicode(0x1f55c),
            EmojiDefault.getEmojiByUnicode(0x1f551),
            EmojiDefault.getEmojiByUnicode(0x1f55d),
            EmojiDefault.getEmojiByUnicode(0x1f552),
            EmojiDefault.getEmojiByUnicode(0x1f55e),
            EmojiDefault.getEmojiByUnicode(0x1f553),
            EmojiDefault.getEmojiByUnicode(0x1f55f),
            EmojiDefault.getEmojiByUnicode(0x1f554),
            EmojiDefault.getEmojiByUnicode(0x1f560),
            EmojiDefault.getEmojiByUnicode(0x1f555),
            EmojiDefault.getEmojiByUnicode(0x1f556),
            EmojiDefault.getEmojiByUnicode(0x1f557),
            EmojiDefault.getEmojiByUnicode(0x1f558),
            EmojiDefault.getEmojiByUnicode(0x1f559),
            EmojiDefault.getEmojiByUnicode(0x1f55a),
            EmojiDefault.getEmojiByUnicode(0x1f561),
            EmojiDefault.getEmojiByUnicode(0x1f562),
            EmojiDefault.getEmojiByUnicode(0x1f563),
            EmojiDefault.getEmojiByUnicode(0x1f564),
            EmojiDefault.getEmojiByUnicode(0x1f565),
            EmojiDefault.getEmojiByUnicode(0x1f566),
            String.valueOf((char) 0x2716),
            String.valueOf((char) 0x2795),
            String.valueOf((char) 0x2796),
            String.valueOf((char) 0x2797),
            String.valueOf((char) 0x2660),
            String.valueOf((char) 0x2665),
            String.valueOf((char) 0x2663),
            String.valueOf((char) 0x2666),
            EmojiDefault.getEmojiByUnicode(0x1f4ae),
            EmojiDefault.getEmojiByUnicode(0x1f4af),
            String.valueOf((char) 0x2714),
            String.valueOf((char) 0x2611),
            EmojiDefault.getEmojiByUnicode(0x1f518),
            EmojiDefault.getEmojiByUnicode(0x1f517),
            String.valueOf((char) 0x27b0),
            String.valueOf((char) 0x3030),
            String.valueOf((char) 0x303d),
            EmojiDefault.getEmojiByUnicode(0x1f531),
            String.valueOf((char) 0x25fc),
            String.valueOf((char) 0x25fb),
            String.valueOf((char) 0x25fe),
            String.valueOf((char) 0x25fd),
            String.valueOf((char) 0x25aa),
            String.valueOf((char) 0x25ab),
            EmojiDefault.getEmojiByUnicode(0x1f53a),
            EmojiDefault.getEmojiByUnicode(0x1f532),
            EmojiDefault.getEmojiByUnicode(0x1f533),
            String.valueOf((char) 0x26ab),
            String.valueOf((char) 0x26aa),
            EmojiDefault.getEmojiByUnicode(0x1f534),
            EmojiDefault.getEmojiByUnicode(0x1f535),
            EmojiDefault.getEmojiByUnicode(0x1f53b),
            String.valueOf((char) 0x2b1c),
            String.valueOf((char) 0x2b1b),
            EmojiDefault.getEmojiByUnicode(0x1f536),
            EmojiDefault.getEmojiByUnicode(0x1f537),
            EmojiDefault.getEmojiByUnicode(0x1f538),
            EmojiDefault.getEmojiByUnicode(0x1f539),
    };
}
